language: swift
os: osx
xcode_project: ./Tapp/Tapp.xcodeproj # path to your xcodeproj folder
xcode_scheme: TappTest
#xcode_workspace: ./Tapp/Tapp.xcworkspace
xcode_destination: platform=macOS
podfile: ./Tapp/Podfile
before_install:
- gem install cocoapods
- pod install --project-directory=./Tapp/
script: 
- set -o pipefail && xcodebuild -workspace ./Tapp/Tapp.xcworkspace -scheme Tapp -destination platform=macOS build test -allowProvisioningUpdates CODE_SIGNING_REQUIRED=NO | xcpretty
- pod lib lint
