language: swift
os: osx
osx_image: xcode10.2
xcode_project: ./Tapp/Tapp.xcodeproj # path to your xcodeproj folder
xcode_scheme: TappTest
#xcode_workspace: ./Tapp/Tapp.xcworkspace
xcode_destination: platform=macOS
podfile: ./Tapp/Podfile
before_install:
- gem install cocoapods
- pod repo update
- pod install --project-directory=./Tapp/
script: 
- set -o pipefail && xcodebuild -workspace ./Tapp/Tapp.xcworkspace -scheme Tapp -destination platform=macOS build test -allowProvisioningUpdates CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
# xctool -project ./Tapp/Tapp.xcodeproj -scheme Tapp build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
