language: swift
os: osx
xcode_project: ./Tapp/Tapp.xcodeproj # path to your xcodeproj folder
xcode_scheme: TappTest
#xcode_workspace: ./Tapp/Tapp.xcworkspace
xcode_destination: platform=macOS
podfile: ./Tapp/Podfile
