language: swift
os: osx
xcode_project: Tapp.xcodeproj # path to your xcodeproj folder
xcode_scheme: Tapp
xcode_destination: platform=macOS
script: set -o pipefail && xcodebuild -project Tapp.xcodeproj -allowProvisioningUpdates -scheme TappScheme -destination platform\=macOS build test | xcpretty
