source 'https://github.com/CocoaPods/Specs.git'
platform :osx, '10.14'
use_frameworks!
project '../Tapp.xcodeproj'
target 'Tapp' do
    pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'AlamofireImage'
   # pod 'SwiftWebSocket'
    pod 'KeychainAccess'
end
