source 'https://github.com/CocoaPods/Specs.git'
platform :osx, '10.14'
use_frameworks!
project './Tapp.xcodeproj'
pre_install do |installer|
  installer.analysis_result.specifications.each do |s|
    if s.name == 'AlamofireImage'
      s.swift_version = '4.2'
    end
    if s.name == 'KeychainAccess'
        s.swift_version = '4.2'
    end
  end
end
target 'Tapp' do
    pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'AlamofireImage'
   # pod 'SwiftWebSocket'
    pod 'KeychainAccess'
end
