source 'https://github.com/CocoaPods/Specs.git'
platform :osx, '10.14'
use_frameworks!
project './Tapp.xcodeproj'
target 'Tapp' do
    pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'AlamofireImage'
   # pod 'SwiftWebSocket'
    pod 'KeychainAccess'
end
    post_install do |installer|
        installer.pods_project.targets.each do |target|
            if ['KeychainAccess'].include? target.name
                target.build_configurations.each do |config|
                    config.build_settings['SWIFT_VERSION'] = '3.2'
                end
            end
        end
    end
